version: '3.2'

services:
  php:
    build:
      context: ./docker/php
    depends_on:
      - db
    volumes:
      - ./:/var/www/html:rw
    ports:
      - 8000:8000

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  node:
    image: node:10
    working_dir: /srv
    volumes:
      - ./:/srv:rw
    command: yarn watch

  mailhog:
    image: mailhog/mailhog:latest
    logging:
      driver: "none"
    ports:
      - 8002:8025

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    working_dir: /application
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - 8001:80